server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: example_route
          uri: https://www.naver.com/
          predicates:
            - Path=/get
          filters:
            - name: AddKakaoOpenApiKeyFilter
            - name: LoggingFilter

  main:
    web-application-type: reactive