server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: vsl_service
          uri: https://openapi.its.go.kr:9443
          predicates:
            - Path=/vslInfo
          filters:
            - name: AddVSLOpenApiFilter
            - name: LoggingFilter

  main:
    web-application-type: reactive


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
